- id: kitchen_freezer_over_temp
  alias: Kitchen freezer over temp
  description: Freezer in kitchen is over 25 degrees
  trigger:
  - above: '25'
    entity_id: sensor.kitchen_freezer_temperature
    platform: numeric_state
  condition: []
  action:
    data_template:
      title: Warning from Buteomont
      message: Kitchen freezer temperature is {{states.sensor.kitchen_freezer_temperature.state}}ยบ
    service: notify.send_sms
  initial_state: true
- id: garage_freezer_over_temp
  alias: Garage freezer over temp
  description: Freezer in garage is over 25 degrees
  trigger:
  - above: '25'
    entity_id: sensor.garage_freezer_temperature
    platform: numeric_state
  condition: []
  action:
    data_template:
      title: Warning from Buteomont
      message: Garage freezer temperature is {{states.sensor.garage_freezer_temperature.state}}ยบ
    service: notify.send_sms
  initial_state: true
- id: high_inside_humidity
  alias: High Humidity
  description: Humidity in the house is too high
  trigger:
  - above: '80'
    entity_id: sensor.house_humidity
    platform: numeric_state
  condition: []
  action:
    data_template:
      title: Warning from Buteomont
      message: The humidity in the house at Buteomont is {{states.sensor.house_humidity.state}}%.
    service: notify.send_sms
  initial_state: true
- id: '1590533016721'
  alias: Basement Humidity Alarm
  description: Basement is too humid
  trigger:
  - entity_id: sensor.basement_humidity
    above: '80'
    platform: numeric_state
  condition: []
  action:
  - data_template:
      title: Warning from Buteomont
      message: Warning - the basement humidity is  {{states.sensor.basement_humidity.state}}%
    service: notify.send_sms
  initial_state: true
- id: reduce_shop_humidity
  alias: Reduce Shop Humidity
  description: Turn on the shop fan if shop humidity is significantly higher than
    ambient
  trigger:
  - for: 00:00:01
    platform: template
    value_template: '{{ states.sensor.shop_humidity.state | int > (states.sensor.outdoor_humidity.state
      | int +5) }}'
  condition: []
  action:
  - data:
      payload: 'ON'
      topic: cmnd/shop_exhaust_fan/Power
    service: mqtt.publish
  initial_state: true
- id: shop_humidity_is_ok
  alias: Shop Humidity Is OK
  description: Turn off the shop fan if shop humidity is not significantly higher
    than ambient
  trigger:
  - for: 00:00:01
    platform: template
    value_template: '{{ states.sensor.shop_humidity.state | int <= (states.sensor.outdoor_humidity.state
      | int  +4) }}'
  condition: []
  action:
  - data:
      payload: 'OFF'
      topic: cmnd/shop_exhaust_fan/Power
    service: mqtt.publish
  initial_state: true
- id: high_inside_temperature
  alias: High House Temperature
  description: Temperature in the house at Buteomont is too high
  trigger:
  - above: '80'
    entity_id: sensor.indoor_temperature
    platform: numeric_state
  condition: []
  action:
    data_template:
      title: Warning from Buteomont
      message: The temperature in Buteomont is {{states.sensor.indoor_temperature.state}}ยบ.
    service: notify.send_sms
  initial_state: true
- id: '1577817691725'
  alias: Notify On Living Room Motion
  description: Send text message when motion is detected in living room
  trigger:
  - entity_id: binary_sensor.living_room_motion
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Motion was detected in the living room at Buteomont!
    service: notify.send_sms
  initial_state: false
- id: '1590533675336'
  alias: Garage Freezer Low Battery Alarm
  description: Send email when battery in freezer sensor is low
  trigger:
  - entity_id: binary_sensor.garage_freezer_battery
    from: '0'
    platform: state
    to: '1'
  condition: []
  action:
  - data_template:
      message: 'The battery in the garage freezer temperature sensor is dying.

        Please replace it at your earliest opportunity.'
      title: Low Battery Notice
    service: notify.send_email
- id: kitchenFreezerLowBatteryAlarm
  alias: Kitchen Freezer Low Battery Alarm
  description: Send email when battery in freezer sensor is low
  trigger:
  - entity_id: binary_sensor.kitchen_freezer_battery
    from: '0'
    platform: state
    to: '1'
  condition: []
  action:
  - data_template:
      message: 'The battery in the kitchen freezer temperature sensor is dying.

        Please replace it at your earliest opportunity.'
      title: Low Battery Notice
    service: notify.send_email
- id: lightningDetectorLowBatteryAlarm
  alias: Lightning Detector Low Battery Alarm
  description: Send email when battery in lightning detector is low
  trigger:
  - entity_id: binary_sensor.lightning_detector_battery
    from: '0'
    platform: state
    to: '1'
  condition: []
  action:
  - data_template:
      message: 'The battery in the lightning detector is dying.

        Please replace it at your earliest opportunity.'
      title: Low Battery Notice
    service: notify.send_email
- id: rainGaugeLowBatteryAlarm
  alias: Rain Gauge Low Battery Alarm
  description: Send email when battery in rain gauge is low
  trigger:
  - entity_id: binary_sensor.rain_gauge_battery
    from: '0'
    platform: state
    to: '1'
  condition: []
  action:
  - data_template:
      message: 'The battery in the rain gauge is dying.

        Please replace it at your earliest opportunity.'
      title: Low Battery Notice
    service: notify.send_email
- id: outdoorTHLowBatteryAlarm
  alias: Outdoor TH Low Battery Alarm
  description: Send email when battery in outdoor temp/humidity sensor is low
  trigger:
  - entity_id: binary_sensor.outdoor_th_battery
    from: '0'
    platform: state
    to: '1'
  condition: []
  action:
  - data_template:
      message: 'The battery in the outdoor temperature/humidity sensor is dying.

        Please replace it at your earliest opportunity.'
      title: Low Battery Notice
    service: notify.send_email
    
- id: driveway_motion_alert
  alias: arriving visitors
  description: Driveway alert when visitors arrive
  trigger:
  - from: 'off'
    to: 'on'
    entity_id: binary_sensor.driveway_alert
    platform: state
  condition: []
  action:
  - service: notify.send_sms
    data_template:
      title: Alert from Buteomont
      message: There are visitors at the house.
  - service: notify.judy_sms
    data_template:
      title: Alert from Buteomont
      message: There are visitors at the house.
  - service: timer.start
    entity_id: timer.driveway_motion
  initial_state: true
- id: cancel_driveway_alert
  alias: Cancel Driveway Alert
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.driveway_motion
  action:
  - service: mqtt.publish
    data:
      payload: '0'
      topic: rtl_433/raspberrypi/devices/DrivewayAlert/rows/0/data
  initial_state: true
    
- id: powell_ridge_motion_alert
  alias: Powell Ridge visitors 
  description: Alert when visitors are on Powell Ridge Road
  trigger:
  - from: 'off'
    to: 'on'
    entity_id: binary_sensor.powell_ridge_alert
    platform: state
  condition: []
  action:
  - service: notify.send_sms
    data_template:
      title: Alert from Buteomont
      message: There are visitors on Powell Ridge Road.
  - service: notify.judy_sms
    data_template:
      title: Alert from Buteomont
      message: There are visitors on Powell Ridge Road.
  - service: timer.start
    entity_id: timer.powell_ridge_motion
  initial_state: true
- id: cancel_powell_ridge_alert
  alias: Cancel Powell Ridge Alert
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.powell_ridge_motion
  action:
  - service: mqtt.publish
    data:
      payload: '0'
      topic: rtl_433/raspberrypi/devices/PowellRidgeAlert/rows/0/data
  initial_state: true

- id: gate_motion_alert
  alias: visitors at gate
  description: Alert when gate opener activated from exit sensor
  trigger:
  - from: 'off'
    to: 'on'
    entity_id: binary_sensor.gate_alert
    platform: state
  condition: []
  action:
  - service: camera.snapshot
    data:
      entity_id: camera.gatecam
      filename: "/tmp/snapshot.jpg"
  - service: notify.send_sms
    data_template:
      title: Alert from Buteomont
      message: There are visitors at the gate.
      data:
        images:
          - '/tmp/snapshot.jpg'
  - service: notify.judy_sms
    data_template:
      title: Alert from Buteomont
      message: There are visitors at the gate.
      data:
        images:
          - '/tmp/snapshot.jpg'
  - service: timer.start
    entity_id: timer.gate_motion
  initial_state: true
- id: 'cancel_gate_alert'
  alias: Cancel Gate Alert
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.gate_motion
  action:
  - service: mqtt.publish
    data:
      payload: '0'
      topic: rtl_433/Pumphouse-pi/devices/GateAlert/rows/0/data
  initial_state: true

- id: '1593048803953'
  alias: Notify On Any Motion
  description: Motion on any motion sensor will send SMS message
  trigger:
  - entity_id: binary_sensor.kitchen_motion
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.living_room_motion
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.study_motion
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      title: Warning from Buteomont
      message: Motion was detected at Buteomont!
    service: notify.send_sms
  initial_state: false
