
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
notify: !include notifiers.yaml

homeassistant:
  customize: !include customize.yaml
  
history:
  exclude:
    entities:
      - sensor.cumulative_rain
      - sensor.cumulative_lightning
      - binary_sensor.lightning_detector_battery
      - binary_sensor.rain_gauge_battery
      - binary_sensor.outdoor_th_battery
      - automation.garage_freezer_over_temp
      - automation.kitchen_freezer_over_temp
      - automation.high_humidity
      - automation.high_house_temperature
      - automation.high_humidity
      - automation.basement_humidity_alarm
      - automation.kitchen_freezer_low_battery_alarm
      - automation.garage_freezer_low_battery_alarm
      - automation.rain_gauge_low_battery_alarm
      - weather.tinyhouse
      - zone.home

sensor:
- platform: cpuspeed

- platform: systemmonitor
  resources:
  - type: disk_use_percent
    arg: /home
  - type: memory_free
  - type: processor_use
  - type: throughput_network_out
    arg: wlan0
  - type: swap_use_percent
  - type: memory_use_percent
  - type: load_1m
 
- platform: mqtt
  name: "Indoor  Humidity"
  device_class: "humidity"
  state_topic: "rtl_433/raspberrypi/devices/Acurite-6045M/A/165/humidity"
  qos: 0
  unit_of_measurement: "pct"
 
- platform: mqtt
  name: "Indoor  Temperature"
  device_class: "temperature"
  state_topic: "rtl_433/raspberrypi/devices/Acurite-6045M/A/165/temperature_F"
  qos: 0
  unit_of_measurement: "ºF"
  
- platform: mqtt
  name: "Kitchen Freezer Temperature"
  device_class: "temperature"
  state_topic: "rtl_433/raspberrypi/devices/Acurite-986/2F/+/temperature_F"
  qos: 0
  unit_of_measurement: "ºF"
  
- platform: mqtt
  name: "Garage Freezer Temperature"
  device_class: "temperature"
  state_topic: "rtl_433/raspberrypi/devices/Acurite-986/1R/+/temperature_F"
  qos: 0
  unit_of_measurement: "ºF"

- platform: mqtt
  name: "Cumulative Rain"
  state_topic: "rtl_433/raspberrypi/devices/Acurite-Rain899/0/+/rain_mm"
  qos: 0
  unit_of_measurement: "mm"

- platform: mqtt
  name: "Cumulative Lightning"
  state_topic: "rtl_433/raspberrypi/devices/Acurite-6045M/A/165/strike_count"
  qos: 0
  unit_of_measurement: "strikes"

- platform: mqtt
  name: "Storm Distance"
  state_topic: "rtl_433/raspberrypi/devices/Acurite-6045M/A/165/storm_dist"
  qos: 0
  unit_of_measurement: "Km"

- platform: mqtt
  name: "Outdoor Temperature"
  device_class: "temperature"
  state_topic: "rtl_433/raspberrypi/devices/Acurite-609TXC/246/temperature_C"
  qos: 0
  unit_of_measurement: "ºF"
  value_template: "{{ (((value | float) * 9/5) + 32) | round(1) }}"

- platform: mqtt
  name: "Outdoor Humidity"
  device_class: "humidity"
  state_topic: "rtl_433/raspberrypi/devices/Acurite-609TXC/246/humidity"
  qos: 0
  unit_of_measurement: "pct"

- platform: mqtt
  name: "Basement Temperature"
  device_class: "temperature"
  state_topic: "tele/basement_th/SENSOR"
  qos: 0
  unit_of_measurement: "ºF"
  value_template: "{{ (((value_json.AM2301.Temperature | float) * 9/5) + 32) | round(1) }}"

- platform: mqtt
  name: "Basement Humidity"
  device_class: "humidity"
  state_topic: "tele/basement_th/SENSOR"
  qos: 0
  unit_of_measurement: "pct"
  value_template: '{{ value_json.AM2301.Humidity | round(0) }}'

- platform: sql
  queries:
  - name: 1 Hour Rain
    query: select abs(round((select state from states where entity_id = 'sensor.cumulative_rain' and state <> "unknown" order by created desc limit 1)-(select state from states where entity_id = 'sensor.cumulative_rain' and state <> "unknown" and created < (datetime('now','-1 hours')) order by created desc  limit 1),2)) as 'delta';
    column: 'delta'
    unit_of_measurement: "mm"
  - name: 24 Hour Rain
    query: select abs(round((select state from states where entity_id = 'sensor.cumulative_rain' and state <> "unknown" order by created desc limit 1)-(select state from states where entity_id = 'sensor.cumulative_rain' and state <> "unknown" and created < (datetime('now','-24 hours')) order by created desc  limit 1),2)) as 'delta';
    column: 'delta'
    unit_of_measurement: "mm"
  - name: Lightning Activity
    query: select abs(round((select state from states where entity_id = 'sensor.cumulative_lightning' and state <> "unknown" order by created desc limit 1)-(select state from states where entity_id = 'sensor.cumulative_lightning' and state <> "unknown" and created < (datetime('now','-60 minutes')) order by created desc  limit 1),0)) as 'delta';
    column: 'delta'
    unit_of_measurement: "Strikes/Hour"

# RSSI indicators
- platform: mqtt
  name: "Rain Gauge Signal Strength"
  state_topic: "rtl_433/raspberrypi/devices/Acurite-Rain899/0/+/rssi"
  qos: 0
  unit_of_measurement: "db"
  value_template: "{{ (value) | round(2) }}"

- platform: mqtt
  name: "Lightning Detector Signal Strength"
  state_topic: "rtl_433/raspberrypi/devices/Acurite-6045M/A/+/rssi"
  qos: 0
  unit_of_measurement: "db"
  value_template: "{{ (value) | round(2) }}"

- platform: mqtt
  name: "Outdoor TH Signal Strength"
  state_topic: "rtl_433/raspberrypi/devices/Acurite-609TXC/+/rssi"
  qos: 0
  unit_of_measurement: "db"
  value_template: "{{ (value) | round(2) }}"

- platform: mqtt
  name: "Garage Freezer Temperature Signal Strength"
  state_topic: "rtl_433/raspberrypi/devices/Acurite-986/1R/18587/rssi"
  qos: 0
  unit_of_measurement: "db"
  value_template: "{{ (value) | round(2) }}"

- platform: mqtt
  name: "Kitchen Freezer Temperature Signal Strength"
  state_topic: "rtl_433/raspberrypi/devices/Acurite-986/2F/32186/rssi"
  qos: 0
  unit_of_measurement: "db"
  value_template: "{{ (value) | round(2) }}"

- platform: mqtt
  name: "Driveway Alert Signal Strength"
  state_topic: "rtl_433/raspberrypi/devices/DrivewayAlert/rssi"
  qos: 0
  unit_of_measurement: "db"
  value_template: "{{ (value) | round(2) }}"

- platform: mqtt
  name: "Kitchen Motion Signal Strength"
  state_topic: "rtl_433/wwwServer/devices/X10-RF/A/1/rssi"
  qos: 0
  unit_of_measurement: "db"
  value_template: "{{ (value) | round(2) }}"

- platform: mqtt
  name: "Study Motion Signal Strength"
  state_topic: "rtl_433/wwwServer/devices/X10-RF/B/4/rssi"
  qos: 0
  unit_of_measurement: "db"
  value_template: "{{ (value) | round(2) }}"

- platform: mqtt
  name: "Living Room Motion Signal Strength"
  state_topic: "rtl_433/wwwServer/devices/X10-RF/E/4/rssi"
  qos: 0
  unit_of_measurement: "db"
  value_template: "{{ (value) | round(2) }}"

# Frequency indicators
- platform: mqtt
  name: "Rain Gauge Frequency"
  state_topic: "rtl_433/raspberrypi/devices/Acurite-Rain899/0/+/freq"
  qos: 0
  unit_of_measurement: "MHz"
  value_template: "{{ (value) | round(4) }}"

- platform: mqtt
  name: "Lightning Detector Frequency"
  state_topic: "rtl_433/raspberrypi/devices/Acurite-6045M/A/+/freq"
  qos: 0
  unit_of_measurement: "MHz"
  value_template: "{{ (value) | round(4) }}"

- platform: mqtt
  name: "Outdoor TH Frequency"
  state_topic: "rtl_433/raspberrypi/devices/Acurite-609TXC/+/freq"
  qos: 0
  unit_of_measurement: "MHz"
  value_template: "{{ (value) | round(4) }}"

- platform: mqtt
  name: "Garage Freezer Temperature Frequency"
  state_topic: "rtl_433/raspberrypi/devices/Acurite-986/1R/18587/freq"
  qos: 0
  unit_of_measurement: "MHz"
  value_template: "{{ (value) | round(4) }}"

- platform: mqtt
  name: "Kitchen Freezer Temperature Frequency"
  state_topic: "rtl_433/raspberrypi/devices/Acurite-986/2F/32186/freq"
  qos: 0
  unit_of_measurement: "MHz"
  value_template: "{{ (value) | round(4) }}"

- platform: mqtt
  name: "Driveway Alert Frequency"
  state_topic: "rtl_433/raspberrypi/devices/DrivewayAlert/freq"
  qos: 0
  unit_of_measurement: "MHz"
  value_template: "{{ (value) | round(4) }}"

- platform: mqtt
  name: "Kitchen Motion Frequency"
  state_topic: "rtl_433/wwwServer/devices/X10-RF/A/1/freq"
  qos: 0
  unit_of_measurement: "MHz"
  value_template: "{{ (value) | round(4) }}"

- platform: mqtt
  name: "Study Motion Frequency"
  state_topic: "rtl_433/wwwServer/devices/X10-RF/B/4/freq"
  qos: 0
  unit_of_measurement: "MHz"
  value_template: "{{ (value) | round(4) }}"

- platform: mqtt
  name: "Living Room Motion Frequency"
  state_topic: "rtl_433/wwwServer/devices/X10-RF/E/4/freq"
  qos: 0
  unit_of_measurement: "MHz"
  value_template: "{{ (value) | round(4) }}"
  
binary_sensor:
- platform: mqtt
  name: "Green Extension Cord"
  state_topic: "stat/green_extension_cord/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  qos: 0

- platform: mqtt
  name: "Living Room Motion"
  state_topic: "rtl_433/wwwServer/devices/X10-RF/E/4/state"
  payload_on: "ON"
  payload_off: "OFF"
  device_class: "motion"
  qos: 0

- platform: mqtt
  name: "Driveway Alert"
  state_topic: "rtl_433/raspberrypi/devices/DrivewayAlert/rows/0/data"
  payload_on: "720"
  payload_off: "0"
  device_class: "motion"
  qos: 0

- platform: mqtt
  name: "Living Room Illuminated"
  state_topic: "rtl_433/wwwServer/devices/X10-RF/E/5/state"
  payload_on: "OFF"
  payload_off: "ON"
  qos: 0

- platform: mqtt
  name: "Study Motion"
  state_topic: "rtl_433/wwwServer/devices/X10-RF/B/4/state"
  payload_on: "ON"
  payload_off: "OFF"
  device_class: "motion"
  qos: 0

- platform: mqtt
  name: "Study Illuminated"
  state_topic: "rtl_433/wwwServer/devices/X10-RF/B/5/state"
  payload_on: "OFF"
  payload_off: "ON"
  qos: 0

- platform: mqtt
  name: "Kitchen Motion"
  state_topic: "rtl_433/wwwServer/devices/X10-RF/A/1/state"
  payload_on: "ON"
  payload_off: "OFF"
  device_class: "motion"
  qos: 0

- platform: mqtt
  name: "Kitchen Illuminated"
  state_topic: "rtl_433/wwwServer/devices/X10-RF/A/2/state"
  payload_on: "OFF"
  payload_off: "ON"
  qos: 0

- platform: mqtt
  name: "Lightning Detector Battery"
  state_topic: "rtl_433/tinyserver/devices/Acurite-6045M/A/+/battery_ok"
  device_class: "battery"
  payload_on: "0"
  payload_off: "1"
  qos: 0
  
- platform: mqtt
  name: "Rain Gauge Battery"
  state_topic: "rtl_433/tinyserver/devices/Acurite-Rain899/0/+/battery_ok"
  device_class: "battery"
  payload_on: "1" #appears to be inverted vs. the lightning detector
  payload_off: "0"
  qos: 0

- platform: mqtt
  name: "Outdoor TH Battery"
  state_topic: "rtl_433/tinyserver/devices/Acurite-609TXC/246/battery_ok"
  device_class: "battery"
  payload_on: "0"
  payload_off: "1"
  qos: 0
  
- platform: mqtt
  name: "Kitchen Freezer Battery"
  state_topic: "rtl_433/raspberrypi/devices/Acurite-986/2F/+/battery_ok"
  device_class: "battery"
  payload_on: "0"
  payload_off: "1"
  qos: 0
  
- platform: mqtt
  name: "Garage Freezer Battery"
  state_topic: "rtl_433/raspberrypi/devices/Acurite-986/1R/+/battery_ok"
  device_class: "battery"
  payload_on: "0" 
  payload_off: "1"
  qos: 0

timer:
  driveway_motion:
    duration: '00:01:00'
    icon: mdi:car-hatchback
