
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
notify: !include notifiers.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml


homeassistant:
  customize: !include customize.yaml
  
history:
  exclude:
    entities:
      - sensor.cumulative_rain
      - sensor.cumulative_lightning
      - binary_sensor.lightning_detector_battery
      - binary_sensor.rain_gauge_battery
      - binary_sensor.outdoor_th_battery
      - automation.garage_freezer_over_temp
      - automation.kitchen_freezer_over_temp
      - automation.high_humidity
      - automation.high_house_temperature
      - automation.high_humidity
      - automation.basement_humidity_alarm
      - automation.kitchen_freezer_low_battery_alarm
      - automation.garage_freezer_low_battery_alarm
      - automation.rain_gauge_low_battery_alarm
      - weather.tinyhouse
      - zone.home

timer:
  driveway_motion:
    duration: '00:01:00'
    icon: mdi:car-hatchback

