- platform: cpuspeed

- platform: systemmonitor
  resources:
  - type: disk_use_percent
    arg: /home
  - type: memory_free
  - type: processor_use
  - type: throughput_network_out
    arg: wlan0
  - type: swap_use_percent
  - type: memory_use_percent
  - type: load_1m
 
############### Shop Sensors
- platform: mqtt
  name: "Shop Temperature"
  device_class: "temperature"
  state_topic: "tele/shop_exhaust_fan/SENSOR"
  qos: 0
  unit_of_measurement: "ºF"
  value_template: "{{ (((value_json.SI7021.Temperature | float) * 9/5) + 32) | round(1) }}"

- platform: mqtt
  name: "Shop Humidity"
  device_class: "humidity"
  state_topic: "tele/shop_exhaust_fan/SENSOR"
  qos: 0
  unit_of_measurement: "pct"
  value_template: '{{ (value_json.SI7021.Humidity | round(0)) -14 }}' # SI7021 module is inaccurate

############### Indoor Sensors
- platform: mqtt
  name: "Indoor  Humidity"
  device_class: "humidity"
  state_topic: "rtl_433/raspberrypi/devices/Acurite-6045M/A/165/humidity"
  qos: 0
  unit_of_measurement: "pct"
 
- platform: mqtt
  name: "Indoor  Temperature"
  device_class: "temperature"
  state_topic: "rtl_433/raspberrypi/devices/Acurite-6045M/A/165/temperature_F"
  qos: 0
  unit_of_measurement: "ºF"
  
- platform: mqtt
  name: "Kitchen Freezer Temperature"
  device_class: "temperature"
  state_topic: "rtl_433/raspberrypi/devices/Acurite-986/2F/+/temperature_F"
  qos: 0
  unit_of_measurement: "ºF"
  
- platform: mqtt
  name: "Garage Freezer Temperature"
  device_class: "temperature"
  state_topic: "rtl_433/raspberrypi/devices/Acurite-986/1R/+/temperature_F"
  qos: 0
  unit_of_measurement: "ºF"

############### Basement Sensors
- platform: mqtt
  name: "Basement Temperature"
  device_class: "temperature"
  state_topic: "tele/basement_th/SENSOR"
  qos: 0
  unit_of_measurement: "ºF"
  value_template: "{{ (((value_json.AM2301.Temperature | float) * 9/5) + 32) | round(1) }}"

- platform: mqtt
  name: "Basement Humidity"
  device_class: "humidity"
  state_topic: "tele/basement_th/SENSOR"
  qos: 0
  unit_of_measurement: "pct"
  value_template: '{{ (value_json.AM2301.Humidity | round(0)) -9 }}' # AM2301 seems to be 9 points too high

############### Outdoor Sensors
- platform: mqtt
  name: "Cumulative Rain"
  state_topic: "rtl_433/raspberrypi/devices/Acurite-Rain899/0/+/rain_mm"
  qos: 0
  unit_of_measurement: "mm"

- platform: mqtt
  name: "Cumulative Lightning"
  state_topic: "rtl_433/raspberrypi/devices/Acurite-6045M/A/165/strike_count"
  qos: 0
  unit_of_measurement: "strikes"

- platform: mqtt
  name: "Storm Distance"
  state_topic: "rtl_433/raspberrypi/devices/Acurite-6045M/A/165/storm_dist"
  qos: 0
  unit_of_measurement: "Km"

- platform: mqtt
  name: "Outdoor Temperature"
  device_class: "temperature"
  state_topic: "rtl_433/raspberrypi/devices/Acurite-609TXC/246/temperature_C"
  qos: 0
  unit_of_measurement: "ºF"
  value_template: "{{ (((value | float) * 9/5) + 32) | round(1) }}"

- platform: mqtt
  name: "Outdoor Humidity"
  device_class: "humidity"
  state_topic: "rtl_433/raspberrypi/devices/Acurite-609TXC/246/humidity"
  qos: 0
  unit_of_measurement: "pct"

- platform: sql
  queries:
  - name: 1 Hour Rain
    query: select abs(round((select state from states where entity_id = 'sensor.cumulative_rain' and state <> "unknown" order by created desc limit 1)-(select state from states where entity_id = 'sensor.cumulative_rain' and state <> "unknown" and created < (datetime('now','-1 hours')) order by created desc  limit 1),2)) as 'delta';
    column: 'delta'
    unit_of_measurement: "mm"
  - name: 24 Hour Rain
    query: select abs(round((select state from states where entity_id = 'sensor.cumulative_rain' and state <> "unknown" order by created desc limit 1)-(select state from states where entity_id = 'sensor.cumulative_rain' and state <> "unknown" and created < (datetime('now','-24 hours')) order by created desc  limit 1),2)) as 'delta';
    column: 'delta'
    unit_of_measurement: "mm"
  - name: Lightning Activity
    query: select abs(round((select state from states where entity_id = 'sensor.cumulative_lightning' and state <> "unknown" order by created desc limit 1)-(select state from states where entity_id = 'sensor.cumulative_lightning' and state <> "unknown" and created < (datetime('now','-60 minutes')) order by created desc  limit 1),0)) as 'delta';
    column: 'delta'
    unit_of_measurement: "Strikes/Hour"

# RSSI indicators
- platform: mqtt
  name: "Rain Gauge Signal Strength"
  state_topic: "rtl_433/raspberrypi/devices/Acurite-Rain899/0/+/rssi"
  qos: 0
  unit_of_measurement: "db"
  value_template: "{{ (value) | round(2) }}"

- platform: mqtt
  name: "Lightning Detector Signal Strength"
  state_topic: "rtl_433/raspberrypi/devices/Acurite-6045M/A/+/rssi"
  qos: 0
  unit_of_measurement: "db"
  value_template: "{{ (value) | round(2) }}"

- platform: mqtt
  name: "Outdoor TH Signal Strength"
  state_topic: "rtl_433/raspberrypi/devices/Acurite-609TXC/+/rssi"
  qos: 0
  unit_of_measurement: "db"
  value_template: "{{ (value) | round(2) }}"

- platform: mqtt
  name: "Garage Freezer Temperature Signal Strength"
  state_topic: "rtl_433/raspberrypi/devices/Acurite-986/1R/18587/rssi"
  qos: 0
  unit_of_measurement: "db"
  value_template: "{{ (value) | round(2) }}"

- platform: mqtt
  name: "Kitchen Freezer Temperature Signal Strength"
  state_topic: "rtl_433/raspberrypi/devices/Acurite-986/2F/32186/rssi"
  qos: 0
  unit_of_measurement: "db"
  value_template: "{{ (value) | round(2) }}"

- platform: mqtt
  name: "Driveway Alert Signal Strength"
  state_topic: "rtl_433/raspberrypi/devices/DrivewayAlert/rssi"
  qos: 0
  unit_of_measurement: "db"
  value_template: "{{ (value) | round(2) }}"

- platform: mqtt
  name: "Kitchen Motion Signal Strength"
  state_topic: "rtl_433/wwwServer/devices/X10-RF/A/1/rssi"
  qos: 0
  unit_of_measurement: "db"
  value_template: "{{ (value) | round(2) }}"

- platform: mqtt
  name: "Study Motion Signal Strength"
  state_topic: "rtl_433/wwwServer/devices/X10-RF/B/4/rssi"
  qos: 0
  unit_of_measurement: "db"
  value_template: "{{ (value) | round(2) }}"

- platform: mqtt
  name: "Living Room Motion Signal Strength"
  state_topic: "rtl_433/wwwServer/devices/X10-RF/E/4/rssi"
  qos: 0
  unit_of_measurement: "db"
  value_template: "{{ (value) | round(2) }}"

# Frequency indicators
- platform: mqtt
  name: "Rain Gauge Frequency"
  state_topic: "rtl_433/raspberrypi/devices/Acurite-Rain899/0/+/freq"
  qos: 0
  unit_of_measurement: "MHz"
  value_template: "{{ (value) | round(4) }}"

- platform: mqtt
  name: "Lightning Detector Frequency"
  state_topic: "rtl_433/raspberrypi/devices/Acurite-6045M/A/+/freq"
  qos: 0
  unit_of_measurement: "MHz"
  value_template: "{{ (value) | round(4) }}"

- platform: mqtt
  name: "Outdoor TH Frequency"
  state_topic: "rtl_433/raspberrypi/devices/Acurite-609TXC/+/freq"
  qos: 0
  unit_of_measurement: "MHz"
  value_template: "{{ (value) | round(4) }}"

- platform: mqtt
  name: "Garage Freezer Temperature Frequency"
  state_topic: "rtl_433/raspberrypi/devices/Acurite-986/1R/18587/freq"
  qos: 0
  unit_of_measurement: "MHz"
  value_template: "{{ (value) | round(4) }}"

- platform: mqtt
  name: "Kitchen Freezer Temperature Frequency"
  state_topic: "rtl_433/raspberrypi/devices/Acurite-986/2F/32186/freq"
  qos: 0
  unit_of_measurement: "MHz"
  value_template: "{{ (value) | round(4) }}"

- platform: mqtt
  name: "Driveway Alert Frequency"
  state_topic: "rtl_433/raspberrypi/devices/DrivewayAlert/freq"
  qos: 0
  unit_of_measurement: "MHz"
  value_template: "{{ (value) | round(4) }}"

- platform: mqtt
  name: "Kitchen Motion Frequency"
  state_topic: "rtl_433/wwwServer/devices/X10-RF/A/1/freq"
  qos: 0
  unit_of_measurement: "MHz"
  value_template: "{{ (value) | round(4) }}"

- platform: mqtt
  name: "Study Motion Frequency"
  state_topic: "rtl_433/wwwServer/devices/X10-RF/B/4/freq"
  qos: 0
  unit_of_measurement: "MHz"
  value_template: "{{ (value) | round(4) }}"

- platform: mqtt
  name: "Living Room Motion Frequency"
  state_topic: "rtl_433/wwwServer/devices/X10-RF/E/4/freq"
  qos: 0
  unit_of_measurement: "MHz"
  value_template: "{{ (value) | round(4) }}"
